### ISSUE TITLE
Not working with ESP8266

### ISSUE THREAD

**Issue by Eisbaeeer** [hencou/Arduino-DCF77#1]
I tried to get it running with ESP8266.
Issue: you must define PIN and Interrupt for ESP who´s not matching with ESP architecture:

dCF77Pin     = DCF77Pin;
dCFinterrupt = DCFinterrupt;	

With ESP8266 only the interrupt pin should be defined.
Is there any solution?
Greets Lars

**Comment by hencou** [comment]
Hi,

You can leave dCFinterupt on "0". See example here: https://github.com/hencou/esphome_components/blob/main/components/dcf77/dcf77_component.h

Regards, Henk

**Comment by Eisbaeeer** [comment]
Hi Henk
Ok, I found it in the lib. You have to define dCFinterrupt with the same pin and not zero.
![image](https://github.com/hencou/Arduino-DCF77/assets/4928271/5d687034-1f62-414d-ad5c-b1b7a527af04)

Thank you for the hint ;-)
