### ISSUE TITLE
let led blinking with signal lengt

### ISSUE THREAD

**Issue by Eisbaeeer** [hencou/Arduino-DCF77#2]
Great lib. It works fine. Now I will blink an LED as a reciving indicator in loop() to get right direction to Frankfurt.
I added this in the lib, but this is not the solution. How can I get the registered pulse in the loop() ?

I added the BUILTIN_LED in this section:
![image](https://github.com/hencou/Arduino-DCF77/assets/4928271/8a72a8ef-c20e-4156-b821-dcda62afdd61)

Greets Lars

**Comment by hencou** [comment]
Hi Lars,

Maybe the pulses are too short to see the LED blinking? I would suggest to set the current time at "Flank up" for example with something like this:
At initialisation:
unint32_t Up = 0;

Then in "Flank up":
Up = millis();

-And then let the LED on if (Up > millis() -1000) for example, so it will be on a second after a "Flank up"

**Comment by Eisbaeeer** [comment]
I added this function to the lib. Pull-request is done.
Greets Lars

**Comment by Eisbaeeer** [comment]
Closed with pull-request #3.
